# Generated by Django 3.0.8 on 2020-09-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_image',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
